import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#83fc8e",
        "on-surface": "#1b1b1e",
        "on-error-container": "#93000a",
        "on-tertiary-fixed": "#002106",
        "secondary-fixed": "#d6e5ef",
        "primary-fixed": "#d8e2ff",
        "surface-bright": "#fbf8fc",
        "tertiary-fixed-dim": "#66df75",
        "secondary-container": "#d3e2ed",
        "inverse-surface": "#303033",
        "on-primary-fixed": "#081b3a",
        "primary": "#031635",
        "on-error": "#ffffff",
        "background": "#fbf8fc",
        "primary-container": "#1a2b4b",
        "on-primary-container": "#8293b8",
        "tertiary": "#001d05",
        "surface-container-high": "#e9e7eb",
        "on-background": "#1b1b1e",
        "on-secondary": "#ffffff",
        "on-tertiary-container": "#2aa946",
        "surface-dim": "#dbd9dc",
        "on-secondary-fixed": "#0f1d25",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        "surface-variant": "#e4e2e5",
        "surface-container-highest": "#e4e2e5",
        "inverse-on-surface": "#f2f0f3",
        "on-tertiary": "#ffffff",
        "surface-tint": "#4e5e81",
        "secondary": "#526069",
        "surface-container-low": "#f5f3f6",
        "outline-variant": "#c5c6cf",
        "outline": "#75777f",
        "error": "#ba1a1a",
        "surface": "#fbf8fc",
        "on-secondary-container": "#56656e",
        "on-primary-fixed-variant": "#364768",
        "surface-container": "#efedf0",
        "on-primary": "#ffffff",
        "tertiary-container": "#00340d",
        "inverse-primary": "#b6c6ef",
        "primary-fixed-dim": "#b6c6ef",
        "on-surface-variant": "#44474e",
      },
      fontFamily: {
        headline: ["Manrope", "Noto Sans JP", "sans-serif"],
        body: ["Noto Sans JP", "sans-serif"],
        label: ["Noto Sans JP", "sans-serif"],
      },
      boxShadow: {
        editorial: "0 12px 40px rgba(27, 27, 30, 0.06)",
      },
    },
  },
  plugins: [],
};

export default config;
